### ISSUE TITLE
Could you make this matrix code usable for other sized matrices?

### ISSUE THREAD

**Issue by jayknowstheway** [adafruit/Adafruit_NeoMatrix#14]
First, thanks for putting the time to create examples and explanations! I have a 8x32 matrix, and when I adjust the size of the rows/columns, the text becomes distorted. I can't easily figure this out.. could you append some code or information regarding this to help get people off the ground? Thanks!!

**Comment by ladyada** [comment]
it totally depends on the way its fabricated. the vendor you bought it from will have the code you need!

**Comment by jayknowstheway** [comment]
thank you Ladyada you are inspirational
