### ISSUE TITLE
MatrixGFXDemo Example compilation error

### ISSUE THREAD

**Issue by robeastwood** [adafruit/Adafruit_NeoMatrix#18]
- Board: ESP8266 NodeMCU
- Arduino IDE version 1.8.13
- Steps to reproduce:
  1. Open MatrixGFXDemo example file
  2. Compile gives error:
```
MatrixGFXDemo:322:1: error: a15 cannot be used in asm here
 }
 ^
MatrixGFXDemo:322:1: error: a15 cannot be used in asm here
exit status 1
a15 cannot be used in asm here
```

Any ideas what is causing this?
Thanks

**Comment by parmarravi** [comment]
Any solution?

**Comment by ladyada** [comment]
this code is writted by @marcmerlin 

@marcmerlin please take a look!

**Comment by marcmerlin** [comment]
Hi,
I'm on vacation so I can't easily test/send a PR, but I can give you the diff.
It's a compiler change in the ESP8266 compiler suite, that I believe is a bug.
you can find that bug in google, I reported it :)
https://www.reddit.com/r/esp8266/comments/ggapj8/new_compiler_breaks_programs_error_a15_cannot_be/

If you apply this fix (really a workaround for the compiler issue), it will work again:
https://github.com/marcmerlin/FastLED_NeoMatrix/commit/be7f3530a799d319a0ec3eb8c1cad55ff624c137

Sorry that I can't easily send a PR (testing that is, I don't have an ESP8266), but I'm very confident this will fix the issue.
Can you apply that patch and submit a PR?
If not, I'll send one in 10 days or so.

**Comment by marcmerlin** [comment]
Sorry for the delay, there you go: https://github.com/adafruit/Adafruit_NeoMatrix/pull/19
The fix was easy, but I had other code that I never merged upstream and had to properly test it before sending the PR.
Turns out @ladyada isn't asking for testing just because, that code I tested on other chips, caused a watchdog reset on ESP8266. This is also now fixed with an extra yield();

**Comment by marcmerlin** [comment]
@parmarravi can you git pull https://github.com/marcmerlin/Adafruit_NeoMatrix and confirm that it works for you and fixes your problem?

**Comment by robeastwood** [comment]
> 
> 
> @parmarravi can you git pull https://github.com/marcmerlin/Adafruit_NeoMatrix and confirm that it works for you and fixes your problem?

Thank you, this compiles now for me ok now
