### ISSUE TITLE
three 16*16 ws2812b matrix to create a 48*16 matrix

### ISSUE THREAD

**Issue by robotcopper** [adafruit/Adafruit_NeoMatrix#24]
Hello,

since i want to create a 48\*16 matrix made of three 16\*16 ws2812b matrix i am looking for a library that let me do that. I am on Arduino nano and every other library (FastLed,...) are to much RAM consuming. Since Neo_Matrix is no consuming that much RAM is it possible to define some thing like:

```
Adafruit_NeoMatrix matrix1 = Adafruit_NeoMatrix(48,16,PIN,
  NEO_MATRIX_BOTTOM + NEO_MATRIX_RIGHT +
  NEO_MATRIX_COLUMNS + NEO_MATRIX_ZIGZAG,
  NEO_GRB + NEO_KHZ800);
```

because for now with neo_matrix we are limited to 32*16 matrix

**Comment by PaintYourDragon** [comment]
Won’t fit in Arduino Nano’s 2K RAM. 48x16x3 = 2.3K. Recommend moving to a more capable microcontroller…RP2040, ESP32, _anything._

**Comment by robotcopper** [comment]
thanks for your fast answer
